### ISSUE TITLE
Memory Leak in DataSource and Delegate?!

### ISSUE THREAD

**Issue by Wolly1985** [luispadron/UIEmptyState#15]
Hello today I check my App for Memory Leaks, when i use  emptyStateDataSource = self in any ViewController the VC will not be release im Memory.

`    public weak var emptyStateDataSource: UIEmptyStateDataSource? {
        get { return objc_getAssociatedObject(self, &Keys.emptyStateDataSource)  as? UIEmptyStateDataSource }
        set { objc_setAssociatedObject(self, &Keys.emptyStateDataSource, newValue, .OBJC_ASSOCIATION_RETAIN) }
    }`

I think the problem is OBJC_ASSOCIATION_RETAIN

has anyone the same problem?

**Comment by luispadron** [comment]
According to #9 this was fixed in the pull request. I don’t currently have time to test it, I can test this weekend. 

However, since you’re having the issue, would you mind modifying the association and seeing what results you get? It’ll be really helpful. 
Thanks for bringing this to my attention.

**Comment by Wolly1985** [comment]
#9 fixed the memory problem but I do not know if it has any impact on other features.

**Comment by luispadron** [comment]
Yah not sure. Have you tried messing around with the association policy like I said above?

Can’t look at this thoroughly until the weekend.

**Comment by luispadron** [comment]
Do you have an example project where I can test this out? 
I've tested this out myself and I'm not getting any leaks when I run Instruments.

**Comment by aashishtamsya** [comment]
`emptyStateDelegate` or `emptyStateDataSource` is still causing the `ViewController` not been removed from the memory.

Found this issue on latest release [Version 3.2.0](https://github.com/luispadron/UIEmptyState/releases/tag/v3.2.0)

it was fixed in PR #9 and subsequently release on [Version 2.0.2](https://github.com/luispadron/UIEmptyState/releases/tag/v2.0.2) but I don't see the changes done for fixing the retain cycle issue in [Version 3.2.0](https://github.com/luispadron/UIEmptyState/releases/tag/v3.2.0)

**Comment by luispadron** [comment]
I’ll take a look at this when I get a chance.

**Comment by aashishtamsya** [comment]
@luispadron Did you get a chance to look into it?

**Comment by luispadron** [comment]
I have not had the time, if you have a fix and can open a pull request feel free to and I can review and check things accordingly

**Comment by luispadron** [comment]
Looking at this now

**Comment by luispadron** [comment]
<img width="1027" alt="screen shot 2018-10-12 at 2 56 01 am" src="https://user-images.githubusercontent.com/13840545/46852865-68caa900-cdca-11e8-967c-19a6d352369c.png">

Been testing this out in a project where I display a controller that uses the empty state and then dismiss that controller. Not getting any leaks in instruments.

One odd thing is that adding a print statement in `deinit`, and the controller that's being dismissed never has it's `deinit` method print. Which means it must not be getting deinitialized? But if that's the case why isn't this showing up in instruments? Removing the use of UIEmptyState delegate and datasource causes the `deinit` to be called and printed, so not sure what's going on. Changing the association from retain to assign, like you mentioned in the old PR was changed because it does nothing. I've tested with all possible values for association and the results are the same, the deinit is not called but instruments shows no leak.
This will require more experimenting.

If you have a project which can clearly replicate a leak in instruments, please send it over, feel free to email me if it's private. This will really help with my debugging.

**Comment by luispadron** [comment]
Actually never mind, it seems like Xcode wasn't rebuilding my test project fully and thus was not able to actually run when I changed to use a different association. Got the `deinit` call to work as expected.

I'll have a release for this tomorrow

**Comment by aashishtamsya** [comment]
> I have not had the time, if you have a fix and can open a pull request feel free to and I can review and check things accordingly

Fix is already present in #9 but it seems that the current source code doesn't contain those fixes.

**Comment by luispadron** [comment]
Fixed in latest release
