### ISSUE TITLE
Overlays TableHeaderView 

### ISSUE THREAD

**Issue by alexanderkorus** [luispadron/UIEmptyState#20]
I have a tableview with a larger tableheaderview, but the emptytableview message is still in the center of the whole view, instead in the middle of the table. Is there a possibility to center the empty view under the table header?
<img width="465" alt="emptytableview" src="https://user-images.githubusercontent.com/14931519/41425009-cb5d83fe-6fff-11e8-9392-9edb4477d5a0.png">

thanks in advance
Alex

**Comment by luispadron** [comment]
Could you provide a project where this issue is replicated so I can test

**Comment by im-jersh** [comment]
this seems like a similar bug that i was experiencing and opened Issue #17 for. I added a link to an example project there but here it is again ([https://github.com/oriyentel/UIEmptyStateBugExample](url)).

as you can tell in the example by viewing the view hierarchy in the View Debugger, the empty state view is being added to the top of the view controller's view. perhaps if this view was instead added and centered in the table/collection to which it is displaying the empty state for then this will be resolved. should be relatively simple for a UIViewController subclass since you're calling the specific `reloadEmptyStateForTableView()` or `reloadEmptyStateForCollectionView()` and providing the table/collection view as a parameter.

**Comment by luispadron** [comment]
Thanks I’ll take a look when I get a chance

**Comment by alexanderkorus** [comment]
Thank you @oriyentel  for sharing the example project.
In my fork (https://github.com/BigAlKo/UIEmptyState), I implemented a (ugly) workaround, by setting a tableHeaderHeight to shift the view down, if I need to. 
I calculate the height of the tableHeader and set the new tableHeaderHeight property in the delegate. I also implement the point method when I set "emptyStateViewCanScroll" to true, because refreshing or any other action to the tableview isn't possible if emptyStateView is shown.

**Comment by luispadron** [comment]
Thanks for the info, I haven’t looked at the library in the bit but I’ll take a look at it tonight and try to see what I can figure out. What would you guys think the best solution would be?

**Comment by luispadron** [comment]
I believe I have a working solution, will ask you to test as soon as I clean it up.
The issue was I was adding the view to the `self.view` of a UIViewController, but this assumes that the tableview takes up the full content of that controller which is incorrect.

Here is what I have now: 

![simulator screen shot - iphone 8 plus - 2018-07-10 at 20 04 44](https://user-images.githubusercontent.com/13840545/42544010-ac1d0988-847c-11e8-8878-6286bf802259.png)

**Comment by luispadron** [comment]
This doesn't fix the issue with table header views, as table header views dont actually change the layout of the table view

<img width="552" alt="screen shot 2018-07-10 at 8 08 14 pm" src="https://user-images.githubusercontent.com/13840545/42544055-fe4e6a1c-847c-11e8-9ecf-ab455f861638.png">

As you can see the table view is still taking up the frame the header view takes up, this is an issue since the empty view is centered in the tableview, will try to find a work around

**Comment by luispadron** [comment]
Should be fixed now! Update to version 3.2.0 and let me know

**Comment by im-jersh** [comment]
can't speak to the table header view but UIEmptyState view behaves as expected for me on 3.2.0. thanks so much!
