### ISSUE TITLE
Detail message not shown due to typo.

### ISSUE THREAD

**Issue by vitobellini** [luispadron/UIEmptyState#6]
emptyStateTitle works fine, but not the detailed one (with or without image)

emptyStateDetailMessage is never shown

```
    var emptyStateTitle: NSAttributedString {
        let attrs = [NSForegroundColorAttributeName: UIColor(red: 0.882, green: 0.890, blue: 0.859, alpha: 1.00),
                     NSFontAttributeName: UIFont.systemFont(ofSize: 22)]
        return NSAttributedString(string: "Main message...", attributes: attrs)
    }
    
    var emptyStateDetailMessage: NSAttributedString {
        let attrs = [NSForegroundColorAttributeName: UIColor.black,
                     NSFontAttributeName: UIFont.systemFont(ofSize: 18)]
        return NSAttributedString(string: "Detailed message...", attributes: attrs)
    }
```

**Comment by luispadron** [comment]
I'm going to need more information than that. 
What version are you using and if you could upload an example of the app that would be best.

**Comment by vitobellini** [comment]
full code here https://pastebin.com/EXjDzTdD

iOS 11 on iPhone 6 Plus (actual device)

**Comment by luispadron** [comment]
You have a typo in your type. `emptyStateDetailMessage` is optional, since you declared it as non-optional UIEmptstate used the default implementation found [here](https://github.com/luispadron/UIEmptyState/blob/master/UIEmptyState/UIEmptyStateDataSource.swift) which returns a nil message thus why you're not seeing your detail message. 

You don't get a compiler warning for this since you are technically fully conformed to `UIEmpstateDataSource` but your `emptyStateDetailMessage` getter will never be called. This is a bit of an issue with Swift itself since it doesn't warn you for obvious typos such as this one. Make `emptyStateDetailMessage` optional and your code will work just fine!

Also, please read the [docs](http://htmlpreview.github.io/?https://github.com/luispadron/UIEmptyState/blob/master/docs/index.html) as it has all the correct names for methods/variables.
