### ISSUE TITLE
Remove protocol extension constraint to UIViewController objects

### ISSUE THREAD

**Issue by raphaelcruzeiro** [luispadron/UIEmptyState#7]
In its current state, UIEmptyState adds a few empty methods to its delegate protocols so that the developer doesn't have to declare all of those methods when conforming to the protocol. This is currently constrained for `UIViewController` objects. Since the methods are all empty declarations that don't use anything from `UIVIewController`, it would be nice to remove this constraint so that the developer will also get those empty methods for free when using a separate data source object.

**Comment by luispadron** [comment]
This seems like something good. Do you have a use case where this would be good? I assumed that users would only want to use this as a view controller conformance however, unneeded constraints are usually bad design so I agree with you. 

If you’d like to go about implementing something like this I’d totally merge it in as long as we try to maintain compatibility. I don’t have time to do the implementation work for at least another week, since super busy with school. 

Thanks for the proposal though!
